markdown: kramdown
highlighter: pygments
permalink: /:title

logo: http://www.gravatar.com/avatar/010666ce377b6b197a754b8299ff4f14?s=100

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]