name: Connor Bode
email_md5: 010666ce377b6b197a754b8299ff4f14
markdown: redcarpet
pygments: true

baseurl: "http://connorbode.github.io/_site"
url: "http://connorbode.github.io/_site"

permalink: :title